### ISSUE TITLE
Rekordbox6 support 

### ISSUE THREAD

**Issue by ShahaRaz** [didiermalenfant/RekordBuddy#1]
Hey, it seems that rekordbox6 has added an XML export option.
does rekordbudy work with it? 

Also, I can't see any open files. Is it coming? :D

**Comment by didiermalenfant** [comment]
I have to take a look and see if the rekordbox version number is handled correctly for whatever they chose to use with this new version. Shouldn't be a problem but I will take a look after the code has been released and everything build correctly again.

**Comment by ShahaRaz** [comment]
> I have to take a look and see if the Rekordbox version number is handled correctly for whatever they chose to use with this new version. Shouldn't be a problem but I will take a look after the code has been released and everything builds correctly again.
////////////////////////
Sure, 
let me know if there you need any kind of help building it (Assuming it's written in Java or Python) :)

**Comment by FunctionDJ** [comment]
> > I have to take a look and see if the Rekordbox version number is handled correctly for whatever they chose to use with this new version. Shouldn't be a problem but I will take a look after the code has been released and everything builds correctly again.
> > ////////////////////////
> > Sure,
> > let me know if there you need any kind of help building it (Assuming it's written in Java or Python) :)

I think Rekord Buddy is written in C++

**Comment by didiermalenfant** [comment]
Let's not close the issue just yet. I'll use this as a reminder of an outstanding task.

**Comment by FunctionDJ** [comment]
> Let's not close the issue just yet. I'll use this as a reminder of an outstanding task.

I mean, that's what they're for =)

**Comment by parameterchild** [comment]
When trying to import a library file from Rekordbox 6 I'm getting the following error: "XML file written by unknown company 'AlphaTheta' "

**Comment by G0510OLD** [comment]
> When trying to import a library file from Rekordbox 6 I'm getting the following error: "XML file written by unknown company 'AlphaTheta' "

same :-(

**Comment by didiermalenfant** [comment]
This is fixed in the repo and will be part of the 2021.1 builds.
