### ISSUE TITLE
Paid Version is not working 

### ISSUE THREAD

**Issue by ShahaRaz** [didiermalenfant/RekordBuddy#2]
The paid version is not working anymore.. 

<img width="626" alt="image" src="https://user-images.githubusercontent.com/55464049/103627289-14311c80-4f46-11eb-9554-29187945a871.png">

<img width="567" alt="image" src="https://user-images.githubusercontent.com/55464049/103627308-1b582a80-4f46-11eb-92aa-eb80f55d5d1d.png">

(no matter what I press, it still doesn't work.

**Comment by didiermalenfant** [comment]
Check out the FAQ on the main [Rekord Buddy](https://rekordbuddy.org) site. Paid version is deprecated and replaced by the free version. Next Audio Labs, the company behind Rekord Buddy no longer exists.
