### ISSUE TITLE
Import rekordbox XML not working

### ISSUE THREAD

**Issue by Yanneckb00** [didiermalenfant/RekordBuddy#20]
Hi,
when I try to import the rekordbox XML file, there is an error _XML written by unknown company 'AlphaTheta'_.

**Comment by JOJ0** [comment]
I think rekordbox 6 is not supported yet: https://github.com/didiermalenfant/RekordBuddy/issues/1

**Comment by Yanneckb00** [comment]
When I open the XML file and change **Company="AlphaTheta"** to **Company="Pioneer DJ"** then it works!

**Comment by didiermalenfant** [comment]
This is fixed in the repo, just need to put out some new builds. Thanks for the helpful solution in the meantime!
