### ISSUE TITLE
Move the manual to Github wiki

### ISSUE THREAD

**Issue by benjaminlewandowski** [didiermalenfant/RekordBuddy#3]

**Comment by benjaminlewandowski** [comment]
Looks like the wiki isn't editable for other users right now. Maybe you have to edit the permissions.

Tried to fork the whole project but unfortunately it is not possible to merge wiki edits.

**Comment by didiermalenfant** [comment]
Let me take a look at the settings. Thanks for offering to help!

**Comment by benjaminlewandowski** [comment]
The least I can do after you open sourcing the project.

**Comment by batsonjay** [comment]
I'm also happy to contribute to the wiki / manual.

**Comment by didiermalenfant** [comment]
The wiki should be modifiable by all now. Let me know if this works and we will close this issue.

**Comment by benjaminlewandowski** [comment]
Looks fine, thank you!

**Comment by benjaminlewandowski** [comment]
Looks like everything is working as expected. Right now I am just copying the text without edits (and the first pages are done) - I will create new Issues for needed edits and expected deletions.
